{  
   'led_name':'nm850',
   'rootdir':'/gpfs/slac/lsst/fs3/g/data/jobHarness/jh_stage/LCA-10134_Cryostat/LCA-10134_Cryostat-0001/',
   'rundir':['/13260/BOT_acq/v0/107781/'],
   #'6845D/BOT_acq/v0/48057/','6845D/BOT_acq/v0/48073/','6855D/BOT_acq/v0/48130/'],
   'scan_size':12,
#   'tmpdir':'/home/combet/beam_BOT/Run3/12x12',
   'tmpdir':'/home/combet/tmp_Run5',
   'ref_raft':'R22',
   'ref_slot':'S11',
   'ref_amps':[5], #[4,5]
   'ref_pix_x':1000,
   'ref_pix_y':256,
   'npix_for_avg':30,
}